// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBipRxxLaMbfxAhd4if84XCW7D6EQ1tJyk',
    appId: '1:520701809814:web:01164a29aca1876da05eb7',
    messagingSenderId: '520701809814',
    projectId: 'gogovernment',
    authDomain: 'gogovernment.firebaseapp.com',
    storageBucket: 'gogovernment.firebasestorage.app',
    measurementId: 'G-PH2VVX2N94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1v1iaI6DiXGhjlV-hWbfsSDIG3Ryys0o',
    appId: '1:520701809814:android:947221af9ff6aa25a05eb7',
    messagingSenderId: '520701809814',
    projectId: 'gogovernment',
    storageBucket: 'gogovernment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBucRWnvS8fJwXfWnyZzSH_AyDVruoR16Q',
    appId: '1:520701809814:ios:318154ebac15c011a05eb7',
    messagingSenderId: '520701809814',
    projectId: 'gogovernment',
    storageBucket: 'gogovernment.firebasestorage.app',
    iosBundleId: 'com.gogovernment.store.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBucRWnvS8fJwXfWnyZzSH_AyDVruoR16Q',
    appId: '1:520701809814:ios:318154ebac15c011a05eb7',
    messagingSenderId: '520701809814',
    projectId: 'gogovernment',
    storageBucket: 'gogovernment.firebasestorage.app',
    iosBundleId: 'com.gogovernment.store.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBipRxxLaMbfxAhd4if84XCW7D6EQ1tJyk',
    appId: '1:520701809814:web:a5ae1694b26f8fa0a05eb7',
    messagingSenderId: '520701809814',
    projectId: 'gogovernment',
    authDomain: 'gogovernment.firebaseapp.com',
    storageBucket: 'gogovernment.firebasestorage.app',
    measurementId: 'G-H05EXHPEY9',
  );
}
